services:
  mysql:
    image: mysql:latest
    container_name: db-proj
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db_proj
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      LANG: C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql-data:

